### ISSUE TITLE
Feature request: Refactor script to output to a mod-manager friendly directory

### ISSUE THREAD

**Issue by hestenet** [acclub/acutils-zsh#2]
If the script is refactored to output the cars folder to a directory like: 

/tmp/clean_windshields/content/cars/<car-name> 

Then any user who uses content manager and/or JGSME could simply drag the content folder into their MODS directory, and use it to mass enable the fix for all cars at once. 

Right now this is a bit of a pain because the default script options output every car into it's own uniquely named directory, without the standard assetto corsa /content/cars tree.

**Comment by gro-ove** [comment]
To be honest, I don’t think a lot of people would use Cygwin+ZSH solution, so I added an option to shaders patch instead. No need to patch stuff, and it also doesn’t remove texture completely, but only hides those semi-transparent bits:
https://acstuff.ru/u/comparison/wfy

**Comment by hestenet** [comment]
That sounds great to me, I'd be happy to close this issue in that case. Is there any ETA on preview50?

**Comment by gro-ove** [comment]
Hopefully I’ll release something if a day or two… The delay with it is because I don’t want to end up with another 170+ MB update, so I’m working on adding proper patch support to CM, with [auto-updates](https://user-images.githubusercontent.com/3996502/53510947-35b25900-3ad0-11e9-844f-97d892926850.png) and
[auto-downloading extra data](https://user-images.githubusercontent.com/3996502/53510949-36e38600-3ad0-11e9-9f80-62d40ca20205.png). That part is somewhat ready, but I’d want to be tested some more first.

**Comment by hestenet** [comment]
That sounds awesome.

Okay going to go ahead and close this for now.
